name: Check link
on:
  schedule:
    - cron: '0 2 * * *'
jobs:
  issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check Link
        run: wget -O - https://pycrystal23-irahbptihfxaezi4c3qraj.streamlit.app/ >/dev/null 2>&1