name: check link on push
on: 
  push: 
    branches:
        - 'main'      
jobs:
  check-link-on-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check Link
        run: wget -O - https://pycrystal23-irahbptihfxaezi4c3qraj.streamlit.app/ >/dev/null 2>&1
      - name:
        run: | 
          pip install pytest supabase
          python3 -m pytest  