name: check db on push
on: 
  push: 
    branches:
        - 'main'      
jobs:
  check-link-on-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: check supabase
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
            pip install supabase pytest
            python3 -m pytest
