name: check link on push
on: 
  push: 
    branches:
        - 'main'      
jobs:
  check-link-on-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check Streamlit Link
        run: |
            pip install supabase
            python3 -m pytest
