name: ping db
on:
  schedule:
    - cron: '0 2 * * *'
jobs:
  check-link:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: run test
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: | 
          pip install supabase pytest
          python3 -m pytest